## run from directory with git repo

Rscript -e 'install.packages("vegan", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("dplyr", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("piecewiseSEM", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("nlme", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("ggplot2", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("ggfortify", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("fossil", repos="http://cran.r-project.org")' 
Rscript -e 'install.packages("lubridate", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("bipartite", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("plyr", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("reshape2", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("RColorBrewer", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("coda", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("nimble", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("igraph", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("parallel", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("randomcoloR", repos="http://cran.r-project.org")'